version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  api:
    build:
      context: .
    container_name: selic-api
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
    depends_on:
      - redis

  worker:
    build:
      context: .
    container_name: selic-worker
    command: npm run worker
    environment:
      - REDIS_HOST=redis
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
    depends_on:
      - redis
